### ISSUE TITLE
Hooks are no longer passed the same object shape for the test parameter (missing fullTitle)

### ISSUE THREAD

**Issue by barrett-vegas-com** [blueimp/wdio-screen-commands#1]
With this change in wdio 5.14.x https://github.com/webdriverio/webdriverio/pull/4354 the before/afterTest hooks are not passed a `test` object that contains a `fullTitle` member.  This means in the example where `cmds.saveScreenshotByTest(test)` is called it will no longer work since it will give `undefined` for `test.fullTitle`.

**Comment by mgrybyk** [comment]
It can be fixed in WebdriverIO itself, you may raise an issue there.

**Comment by blueimp** [comment]
Closing this thanks to the fix in https://github.com/webdriverio/webdriverio/pull/4574.

Thanks for the report @barrett-vegas-com and the thanks for the fix in WebdriverIO @mgrybyk.
